spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_auto_create_table_demo?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: 

server:
  port: 8080